name: AsyncAnticheat
version: ${version}
main: md.thomas.asyncanticheat.bukkit.AsyncAnticheatBukkitPlugin
api-version: "1.21"
folia-supported: true
description: Async anticheat packet capture and streaming via PacketEvents
authors:
  - th0rgal
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

commands:
  aac:
    description: AsyncAnticheat main command - dashboard status and recording
    usage: /aac [record|status]
    aliases: [asyncanticheat]

permissions:
  asyncanticheat.record:
    description: Allows using AsyncAnticheat in-game recording (/aac record)
    default: op


